version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pocki-bot-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - pocki-network

networks:
  pocki-network:
    driver: bridge